logging:
  file:
    name: logs/application.log

spring:
  ssl:
    bundle:
      jks:
        mykeystore1:
          key:
            alias: "acme"
            password: "password"
          keystore:
            location: "classpath:certs/mykeystore1.p12"
            password: "password"
        mytruststore1:
          truststore:
            location: "classpath:certs/mytruststore1.jks"
            password: "changeit"

  boot:
    admin:
      client:
        url: http://localhost:9000
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
  security:
    user:
      name: client
      password: client

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true